<a href="https://colab.research.google.com/github/deveshkumawat258/pythonwork/blob/main/DAY_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY 7
  
  

```
# This is formatted as code
```

DATA analytics:=> analysis of any data
	cricket= sanjay bangur
	data analysis?
	field=> data analysis =>pattern(service)


	DATA science
	problem understanding => data collection =>(cleansing) data analysis =>
	data engineer => ,machine learning => dashboard

	DATA analysis: python,SQL,POWERBI other main tools

	pyhton=> libraries(NumPy,Pandas)
	List=> stores data but does not allow to perform any operation directly
	so we use NumPy (Numerical python)

	NumPy(used to perform calculation on data
	use a nD array to store any data
  array=> data structure for storing data in continuos memory location

In [3]:
import numpy as n
arr=n.arange(10) #arange used to create an aaray

print(type(arr))
print(arr.size)


<class 'numpy.ndarray'>
10


In [4]:
arr=n.ndarray(8)  #ndarray assign random values in array
arr

array([1.39263765e-315, 0.00000000e+000, 6.79038653e-313, 1.39083835e-315,
       0.00000000e+000, 0.00000000e+000, 9.88131292e-324, 0.00000000e+000])

In [13]:
z=n.array([[7,8,9,4],
            [3,4,2,6],
            [2,4,6,1]])
print(z.size)  #attributes=>characteristics  gives the total elements size
print(z.shape)   #tells the dimension of the array
z
z.T    #.T is used to transpose the array

12
(3, 4)


array([[7, 3, 2],
       [8, 4, 4],
       [9, 2, 6],
       [4, 6, 1]])

In [19]:
z1=n.arange(12)
z.shape
print(z)
z=z.reshape(2,6) #reshape the array according to the size factor
print(z)

[[7 8 9 4 3 4]
 [2 6 2 4 6 1]]
[[7 8 9 4 3 4]
 [2 6 2 4 6 1]]


In [20]:
z.tolist()

[[7, 8, 9, 4, 3, 4], [2, 6, 2, 4, 6, 1]]

In [23]:
arr=n.array([1,2.3,3.5,5])
print(arr)

arr=n.array([19,2,3.5,4],dtype='float')  #used to change the data type
print(arr)

[1.  2.3 3.5 5. ]
[19.   2.   3.5  4. ]


In [24]:
n.zeros(4)  #print zero array

array([0., 0., 0., 0.])

In [25]:
n.ones((3,4),dtype='float') #print unit matrix array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

pandas


datatype


builin NumPy


powerful library


Series and dataframe


series can be called as ndarray or 1column


1 column +1 column => dataframe

In [44]:
import pandas as pd
marks=pd.Series([12,13,14,15],index=['A','B','C',"D"])
print(type(marks))
print(marks.index)
print(marks)
marks["D"]="Hii"
marks
marks.to_dict()# show the array in form of dicionary

<class 'pandas.core.series.Series'>
Index(['A', 'B', 'C', 'D'], dtype='object')
A    12
B    13
C    14
D    15
dtype: int64


{'A': 12, 'B': 13, 'C': 14, 'D': 'Hii'}

In [37]:

arr=n.array([12,45,22,'gharpe ja'])
d=pd.Series(arr)
d

0           12
1           45
2           22
3    gharpe ja
dtype: object

In [45]:
marks=pd.Series([12,13,14,15],index=['A','B','C',"D"])
marks.max()
marks.idxmax()


'D'

In [50]:
marks=pd.Series( [1,2,3,4,45,5,5,6,7,87,88,])
marks.value_counts() #counts and prints the values how much time they occured
marks.sort_values(ignore_index=True) #do not touch index

0      1
1      2
2      3
3      4
4      5
5      5
6      6
7      7
8     45
9     87
10    88
dtype: int64

In [54]:
print(marks.sort_values()) #sort the array

0      1
1      2
2      3
3      4
5      5
6      5
7      6
8      7
4     45
9     87
10    88
dtype: int64


In [55]:
marks.value_counts()

5     2
1     1
2     1
3     1
4     1
45    1
6     1
7     1
87    1
88    1
Name: count, dtype: int64

In [58]:
def func(num):
  if(num%2==0):
    return num+5
  else:
    return num+10
marks=pd.Series( [1,2,3,4,45,5,5,6,7,87,88,])
marks.apply(func)  #we can apply the function that we have made

0     11
1      7
2     13
3      9
4     55
5     15
6     15
7     11
8     17
9     97
10    93
dtype: int64

In [61]:
rrr=pd.DataFrame({"product":["A","B","C"],"price":[100,200,300]})
type(rrr["price"]) #when use type it is series because when we use column it show in series not dataframe

pandas.core.series.Series

In [62]:
rrr["price"] #to access the column

0    100
1    200
2    300
Name: price, dtype: int64

In [63]:
rrr

product  price
0       A    100
1       B    200
2       C    300

In [64]:
rrr[rrr["price"]>100]  #TO FILTER THE DATA

product  price
1       B    200
2       C    300

In [ ]:
# Tomorrow Exploratory Data Analysis (EDA)

 TASK 1 -find out a way through which we can run each linux command thorugh python

 TASK 2 - create a program in which the user will give an input for which type of video he wants to view (automated youtube video run) and 1st video should run automatically